### ISSUE TITLE
active record model's text fields causing "stack level too deep"

### ISSUE THREAD

**Issue by mattsly** [hunterae/table-for#11]
Adding the following column, which is `text`, I'm getting "stack level too deep" errors

`<% table.column :body, :header => "Contents" %>
`
(I also get it when I add `:formatter => [:truncate, 25]` as part of that, which I initially thought was involved...but omitting that and it still occurs)

All other column types (tested so far) work great. My work around is to stub a method into the Model to truncate the first N characters and it works OK, but a bit hacky...

ruby-2.0.0-p648 & Rails 3.2.19, fwiw

**Comment by hunterae** [comment]
Thanks for reporting @mattsly. I'll try and look into that this week and reach out if I have any further questions.

**Comment by hunterae** [comment]
Hey @mattsly . I had a chance to look into this, and the issue seems to revolve around the name of your table column "body". The reason is that internally the gem defines a body of code with the same name, and the dual definition ends up causing the infinite call cycle. 

I am in the process of doing a full-rewrite of this gem so I can make sure this isn't an issue in the new version. In the meantime, here are two potential workarounds for the issue:

```
<%= table_for @robots do |table| %>
  <%= table.column header: "Body" do |robot| %>
    <%= robot.body.truncate(25) %>
  <% end %>

  <%= table.column header: "Body", data: lambda {|robot| robot.body.truncate(25) } %>
<% end %>
```

**Comment by mattsly** [comment]
👍  nice thanks for diagnosis and the work around! 🍻
